insert into public.us_states (name, code, active)
values
  ('Alabama', 'AL', true),
  ('Alaska', 'AK', true),
  ('Arizona', 'AZ', true),
  ('Arkansas', 'AR', true),
  ('California', 'CA', true),
  ('Colorado', 'CO', true),
  ('Connecticut', 'CT', true),
  ('Delaware', 'DE', true),
  ('Florida', 'FL', true),
  ('Georgia', 'GA', true),
  ('Hawaii', 'HI', true),
  ('Idaho', 'ID', true),
  ('Illinois', 'IL', true),
  ('Indiana', 'IN', true),
  ('Iowa', 'IA', true),
  ('Kansas', 'KS', true),
  ('Kentucky', 'KY', true),
  ('Louisiana', 'LA', true),
  ('Maine', 'ME', true),
  ('Maryland', 'MD', true),
  ('Massachusetts', 'MA', true),
  ('Michigan', 'MI', true),
  ('Minnesota', 'MN', true),
  ('Mississippi', 'MS', true),
  ('Missouri', 'MO', true),
  ('Montana', 'MT', true),
  ('Nebraska', 'NE', true),
  ('Nevada', 'NV', true),
  ('New Hampshire', 'NH', true),
  ('New Jersey', 'NJ', true),
  ('New Mexico', 'NM', true),
  ('New York', 'NY', true),
  ('North Carolina', 'NC', true),
  ('North Dakota', 'ND', true),
  ('Ohio', 'OH', true),
  ('Oklahoma', 'OK', true),
  ('Oregon', 'OR', true),
  ('Pennsylvania', 'PA', true),
  ('Rhode Island', 'RI', true),
  ('South Carolina', 'SC', true),
  ('South Dakota', 'SD', true),
  ('Tennessee', 'TN', true),
  ('Texas', 'TX', true),
  ('Utah', 'UT', true),
  ('Vermont', 'VT', true),
  ('Virginia', 'VA', true),
  ('Washington', 'WA', true),
  ('West Virginia', 'WV', true),
  ('Wisconsin', 'WI', true),
  ('Wyoming', 'WY', true),
  ('Washington D.C.', 'DC', true)
on conflict (code) do update
set
  name = excluded.name,
  active = excluded.active;

with city_seed (state_code, name, is_major) as (
  values
    ('AL', 'Birmingham', true),
    ('AL', 'Montgomery', true),
    ('AL', 'Huntsville', true),
    ('AL', 'Mobile', true),
    ('AL', 'Tuscaloosa', true),
    ('AL', 'Otra', false),
    ('AK', 'Anchorage', true),
    ('AK', 'Fairbanks', true),
    ('AK', 'Juneau', true),
    ('AK', 'Wasilla', true),
    ('AK', 'Otra', false),
    ('AZ', 'Phoenix', true),
    ('AZ', 'Tucson', true),
    ('AZ', 'Mesa', true),
    ('AZ', 'Chandler', true),
    ('AZ', 'Scottsdale', true),
    ('AZ', 'Yuma', true),
    ('AZ', 'Otra', false),
    ('AR', 'Little Rock', true),
    ('AR', 'Fayetteville', true),
    ('AR', 'Fort Smith', true),
    ('AR', 'Springdale', true),
    ('AR', 'Jonesboro', true),
    ('AR', 'Otra', false),
    ('CA', 'Los Angeles', true),
    ('CA', 'San Diego', true),
    ('CA', 'San Francisco', true),
    ('CA', 'Sacramento', true),
    ('CA', 'Fresno', true),
    ('CA', 'San Jose', true),
    ('CA', 'Oakland', true),
    ('CA', 'Long Beach', true),
    ('CA', 'Bakersfield', true),
    ('CA', 'Anaheim', true),
    ('CA', 'Otra', false),
    ('CO', 'Denver', true),
    ('CO', 'Colorado Springs', true),
    ('CO', 'Aurora', true),
    ('CO', 'Fort Collins', true),
    ('CO', 'Lakewood', true),
    ('CO', 'Pueblo', true),
    ('CO', 'Otra', false),
    ('CT', 'Bridgeport', true),
    ('CT', 'New Haven', true),
    ('CT', 'Stamford', true),
    ('CT', 'Hartford', true),
    ('CT', 'Waterbury', true),
    ('CT', 'Norwalk', true),
    ('CT', 'Otra', false),
    ('DE', 'Wilmington', true),
    ('DE', 'Dover', true),
    ('DE', 'Newark', true),
    ('DE', 'Middletown', true),
    ('DE', 'Otra', false),
    ('FL', 'Miami', true),
    ('FL', 'Orlando', true),
    ('FL', 'Tampa', true),
    ('FL', 'Jacksonville', true),
    ('FL', 'Fort Lauderdale', true),
    ('FL', 'Tallahassee', true),
    ('FL', 'Hialeah', true),
    ('FL', 'St. Petersburg', true),
    ('FL', 'Cape Coral', true),
    ('FL', 'Otra', false),
    ('GA', 'Atlanta', true),
    ('GA', 'Augusta', true),
    ('GA', 'Columbus', true),
    ('GA', 'Savannah', true),
    ('GA', 'Athens', true),
    ('GA', 'Macon', true),
    ('GA', 'Otra', false),
    ('HI', 'Honolulu', true),
    ('HI', 'Hilo', true),
    ('HI', 'Kailua', true),
    ('HI', 'Kapolei', true),
    ('HI', 'Kaneohe', true),
    ('HI', 'Otra', false),
    ('ID', 'Boise', true),
    ('ID', 'Meridian', true),
    ('ID', 'Nampa', true),
    ('ID', 'Idaho Falls', true),
    ('ID', 'Pocatello', true),
    ('ID', 'Otra', false),
    ('IL', 'Chicago', true),
    ('IL', 'Aurora', true),
    ('IL', 'Naperville', true),
    ('IL', 'Joliet', true),
    ('IL', 'Springfield', true),
    ('IL', 'Rockford', true),
    ('IL', 'Elgin', true),
    ('IL', 'Peoria', true),
    ('IL', 'Otra', false),
    ('IN', 'Indianapolis', true),
    ('IN', 'Fort Wayne', true),
    ('IN', 'Evansville', true),
    ('IN', 'South Bend', true),
    ('IN', 'Carmel', true),
    ('IN', 'Gary', true),
    ('IN', 'Otra', false),
    ('IA', 'Des Moines', true),
    ('IA', 'Cedar Rapids', true),
    ('IA', 'Davenport', true),
    ('IA', 'Sioux City', true),
    ('IA', 'Iowa City', true),
    ('IA', 'Otra', false),
    ('KS', 'Wichita', true),
    ('KS', 'Overland Park', true),
    ('KS', 'Kansas City', true),
    ('KS', 'Topeka', true),
    ('KS', 'Olathe', true),
    ('KS', 'Otra', false),
    ('KY', 'Louisville', true),
    ('KY', 'Lexington', true),
    ('KY', 'Bowling Green', true),
    ('KY', 'Owensboro', true),
    ('KY', 'Covington', true),
    ('KY', 'Otra', false),
    ('LA', 'New Orleans', true),
    ('LA', 'Baton Rouge', true),
    ('LA', 'Shreveport', true),
    ('LA', 'Lafayette', true),
    ('LA', 'Lake Charles', true),
    ('LA', 'Otra', false),
    ('ME', 'Portland', true),
    ('ME', 'Lewiston', true),
    ('ME', 'Bangor', true),
    ('ME', 'South Portland', true),
    ('ME', 'Auburn', true),
    ('ME', 'Otra', false),
    ('MD', 'Baltimore', true),
    ('MD', 'Frederick', true),
    ('MD', 'Rockville', true),
    ('MD', 'Gaithersburg', true),
    ('MD', 'Bowie', true),
    ('MD', 'Annapolis', true),
    ('MD', 'Otra', false),
    ('MA', 'Boston', true),
    ('MA', 'Worcester', true),
    ('MA', 'Springfield', true),
    ('MA', 'Cambridge', true),
    ('MA', 'Lowell', true),
    ('MA', 'Quincy', true),
    ('MA', 'Otra', false),
    ('MI', 'Detroit', true),
    ('MI', 'Grand Rapids', true),
    ('MI', 'Warren', true),
    ('MI', 'Sterling Heights', true),
    ('MI', 'Ann Arbor', true),
    ('MI', 'Lansing', true),
    ('MI', 'Otra', false),
    ('MN', 'Minneapolis', true),
    ('MN', 'St. Paul', true),
    ('MN', 'Rochester', true),
    ('MN', 'Duluth', true),
    ('MN', 'Bloomington', true),
    ('MN', 'Otra', false),
    ('MS', 'Jackson', true),
    ('MS', 'Gulfport', true),
    ('MS', 'Southaven', true),
    ('MS', 'Biloxi', true),
    ('MS', 'Hattiesburg', true),
    ('MS', 'Otra', false),
    ('MO', 'Kansas City', true),
    ('MO', 'St. Louis', true),
    ('MO', 'Springfield', true),
    ('MO', 'Columbia', true),
    ('MO', 'Independence', true),
    ('MO', 'Otra', false),
    ('MT', 'Billings', true),
    ('MT', 'Missoula', true),
    ('MT', 'Great Falls', true),
    ('MT', 'Bozeman', true),
    ('MT', 'Helena', true),
    ('MT', 'Otra', false),
    ('NE', 'Omaha', true),
    ('NE', 'Lincoln', true),
    ('NE', 'Bellevue', true),
    ('NE', 'Grand Island', true),
    ('NE', 'Kearney', true),
    ('NE', 'Otra', false),
    ('NV', 'Las Vegas', true),
    ('NV', 'Henderson', true),
    ('NV', 'Reno', true),
    ('NV', 'North Las Vegas', true),
    ('NV', 'Sparks', true),
    ('NV', 'Otra', false),
    ('NH', 'Manchester', true),
    ('NH', 'Nashua', true),
    ('NH', 'Concord', true),
    ('NH', 'Dover', true),
    ('NH', 'Rochester', true),
    ('NH', 'Otra', false),
    ('NJ', 'Newark', true),
    ('NJ', 'Jersey City', true),
    ('NJ', 'Paterson', true),
    ('NJ', 'Elizabeth', true),
    ('NJ', 'Trenton', true),
    ('NJ', 'Camden', true),
    ('NJ', 'Otra', false),
    ('NM', 'Albuquerque', true),
    ('NM', 'Las Cruces', true),
    ('NM', 'Rio Rancho', true),
    ('NM', 'Santa Fe', true),
    ('NM', 'Roswell', true),
    ('NM', 'Otra', false),
    ('NY', 'New York City', true),
    ('NY', 'Buffalo', true),
    ('NY', 'Rochester', true),
    ('NY', 'Yonkers', true),
    ('NY', 'Syracuse', true),
    ('NY', 'Albany', true),
    ('NY', 'New Rochelle', true),
    ('NY', 'Mount Vernon', true),
    ('NY', 'Otra', false),
    ('NC', 'Charlotte', true),
    ('NC', 'Raleigh', true),
    ('NC', 'Greensboro', true),
    ('NC', 'Durham', true),
    ('NC', 'Winston-Salem', true),
    ('NC', 'Fayetteville', true),
    ('NC', 'Otra', false),
    ('ND', 'Fargo', true),
    ('ND', 'Bismarck', true),
    ('ND', 'Grand Forks', true),
    ('ND', 'Minot', true),
    ('ND', 'West Fargo', true),
    ('ND', 'Otra', false),
    ('OH', 'Columbus', true),
    ('OH', 'Cleveland', true),
    ('OH', 'Cincinnati', true),
    ('OH', 'Toledo', true),
    ('OH', 'Akron', true),
    ('OH', 'Dayton', true),
    ('OH', 'Otra', false),
    ('OK', 'Oklahoma City', true),
    ('OK', 'Tulsa', true),
    ('OK', 'Norman', true),
    ('OK', 'Broken Arrow', true),
    ('OK', 'Lawton', true),
    ('OK', 'Otra', false),
    ('OR', 'Portland', true),
    ('OR', 'Eugene', true),
    ('OR', 'Salem', true),
    ('OR', 'Gresham', true),
    ('OR', 'Hillsboro', true),
    ('OR', 'Bend', true),
    ('OR', 'Otra', false),
    ('PA', 'Philadelphia', true),
    ('PA', 'Pittsburgh', true),
    ('PA', 'Allentown', true),
    ('PA', 'Erie', true),
    ('PA', 'Reading', true),
    ('PA', 'Scranton', true),
    ('PA', 'Otra', false),
    ('RI', 'Providence', true),
    ('RI', 'Warwick', true),
    ('RI', 'Cranston', true),
    ('RI', 'Pawtucket', true),
    ('RI', 'East Providence', true),
    ('RI', 'Otra', false),
    ('SC', 'Charleston', true),
    ('SC', 'Columbia', true),
    ('SC', 'North Charleston', true),
    ('SC', 'Mount Pleasant', true),
    ('SC', 'Rock Hill', true),
    ('SC', 'Otra', false),
    ('SD', 'Sioux Falls', true),
    ('SD', 'Rapid City', true),
    ('SD', 'Aberdeen', true),
    ('SD', 'Brookings', true),
    ('SD', 'Watertown', true),
    ('SD', 'Otra', false),
    ('TN', 'Nashville', true),
    ('TN', 'Memphis', true),
    ('TN', 'Knoxville', true),
    ('TN', 'Chattanooga', true),
    ('TN', 'Clarksville', true),
    ('TN', 'Murfreesboro', true),
    ('TN', 'Otra', false),
    ('TX', 'Houston', true),
    ('TX', 'Dallas', true),
    ('TX', 'San Antonio', true),
    ('TX', 'Austin', true),
    ('TX', 'Fort Worth', true),
    ('TX', 'El Paso', true),
    ('TX', 'Arlington', true),
    ('TX', 'Corpus Christi', true),
    ('TX', 'Laredo', true),
    ('TX', 'McAllen', true),
    ('TX', 'Otra', false),
    ('UT', 'Salt Lake City', true),
    ('UT', 'West Valley City', true),
    ('UT', 'Provo', true),
    ('UT', 'West Jordan', true),
    ('UT', 'Orem', true),
    ('UT', 'Otra', false),
    ('VT', 'Burlington', true),
    ('VT', 'South Burlington', true),
    ('VT', 'Rutland', true),
    ('VT', 'Barre', true),
    ('VT', 'Montpelier', true),
    ('VT', 'Otra', false),
    ('VA', 'Virginia Beach', true),
    ('VA', 'Norfolk', true),
    ('VA', 'Chesapeake', true),
    ('VA', 'Richmond', true),
    ('VA', 'Arlington', true),
    ('VA', 'Alexandria', true),
    ('VA', 'Otra', false),
    ('WA', 'Seattle', true),
    ('WA', 'Spokane', true),
    ('WA', 'Tacoma', true),
    ('WA', 'Vancouver', true),
    ('WA', 'Bellevue', true),
    ('WA', 'Everett', true),
    ('WA', 'Otra', false),
    ('WV', 'Charleston', true),
    ('WV', 'Huntington', true),
    ('WV', 'Morgantown', true),
    ('WV', 'Parkersburg', true),
    ('WV', 'Wheeling', true),
    ('WV', 'Otra', false),
    ('WI', 'Milwaukee', true),
    ('WI', 'Madison', true),
    ('WI', 'Green Bay', true),
    ('WI', 'Kenosha', true),
    ('WI', 'Racine', true),
    ('WI', 'Appleton', true),
    ('WI', 'Otra', false),
    ('WY', 'Cheyenne', true),
    ('WY', 'Casper', true),
    ('WY', 'Laramie', true),
    ('WY', 'Gillette', true),
    ('WY', 'Rock Springs', true),
    ('WY', 'Otra', false),
    ('DC', 'Washington', true),
    ('DC', 'Otra', false)
)
insert into public.us_cities (state_id, name, is_major, active)
select
  s.id,
  c.name,
  c.is_major,
  true
from city_seed c
join public.us_states s on s.code = c.state_code
on conflict (state_id, name) do update
set
  is_major = excluded.is_major,
  active = excluded.active;
